# Generated by Django 2.2.7 on 2019-11-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(default='Jack', max_length=50, unique=True),
        ),
    ]
