# Generated by Django 2.2.7 on 2019-11-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_auto_20191108_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='lines',
            field=models.ManyToManyField(blank=True, related_name='stations', to='stations.Line'),
        ),
    ]
